### ISSUE TITLE
Feature: Replace heartbeat with gRPC connection monitoring

### ISSUE THREAD

**Issue by drasko** [ultravioletrs/cocos#104]
### Is your feature request related to a problem? Please describe.

gRPC connection monitoring should be enough, it does have keepalive internaly.

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Install handler on gRPC disconnect to update `Backends` table.

### Indicate the importance of this feature to you.

Must-have

**Comment by SammyOina** [comment]
will be resolved by https://github.com/ultravioletrs/prism/pull/167
