### ISSUE TITLE
Feature: Make distinction multiple runs of a computation for logs and events

### ISSUE THREAD

**Issue by SammyOina** [ultravioletrs/cocos#142]
### Is your feature request related to a problem? Please describe.

Multiple runs of computations need to have distinguished logs and events

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Multiple runs of computations need to have distinguished logs and events

### Indicate the importance of this feature to you.

Must-have

**Comment by drasko** [comment]
Make a collapsable boxes/lists, so that only actual.computation is opened, and all other collapsed. In the title keep computation name and timestamp, and a backend on which it is executed as well
