### ISSUE TITLE
Feature: Enable agent to receive and pass custom arguments

### ISSUE THREAD

**Issue by SammyOina** [ultravioletrs/cocos#169]
### Is your feature request related to a problem? Please describe.

agent doen't pass arguments currently to algo

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Agent should be able to receive and pass custom arguments to the algorithm as defined in the manifest

### Indicate the importance of this feature to you.

Must-have

**Comment by SammyOina** [comment]
filenames are currently maintained hence no need for this

**Comment by rodneyosodo** [comment]
I just wanted to let you know that this is still needed. Not all algorithms need files. For example, when making inference you need input https://github.com/ultravioletrs/ai/blob/main/burn-algorithms/README.md#addition-inference
