### ISSUE TITLE
Feature: Enhance attested TLS

### ISSUE THREAD

**Issue by danko-miladinovic** [ultravioletrs/cocos#192]
### Is your feature request related to a problem? Please describe.

The attested TLS mechanism should be upgraded to include custom TLS extension. The content of the extension should be the attestation report. 

The report data field of the attestation report should still have the hash of the public key, but it should also have a random nonce added to it.

### Describe the feature you are requesting, as well as the possible use case(s) for it.

The feature should align with: https://datatracker.ietf.org/doc/draft-fossati-tls-attestation/

### Indicate the importance of this feature to you.

Must-have

**Comment by drasko** [comment]
Please also do not forget in-handshake attestation. This one is extremely important and urgent!

**Comment by dborovcanin** [comment]
This is a requirement for #160.

**Comment by dborovcanin** [comment]
@SammyOina Please test as soon as PR is ready. This one is a priority.
