### ISSUE TITLE
Feature: Add option for more user friendly attestation report

### ISSUE THREAD

**Issue by SammyOina** [ultravioletrs/cocos#255]
### Is your feature request related to a problem? Please describe.

attestation report is in binary and not viewable by users

### Describe the feature you are requesting, as well as the possible use case(s) for it.

represent report in json or some other user friendly way

### Indicate the importance of this feature to you.

Should-have

**Comment by dborovcanin** [comment]
We need to understand attestations better to be able to provide more user-friendly reports.

**Comment by SammyOina** [comment]
https://cloud.google.com/confidential-computing/confidential-vm/docs/verify-firmware @dborovcanin seems google uses the same report format we  use serialized using protobuf https://github.com/google/go-sev-guest. https://cloud.google.com/confidential-computing/confidential-vm/docs/attestation
