### ISSUE TITLE
Bug: Cocos-cli gets stuck while uploading datasets or algo to the agent

### ISSUE THREAD

**Issue by WashingtonKK** [ultravioletrs/cocos#262]
### What were you trying to achieve?

Upload algorithm and dataset using the cli

### What are the expected results?

Dataset and algorithm should be uploaded to the agent

### What are the received results?

The progressbar gets stuck for about 2 minutes then completes the operation.

### Steps To Reproduce

Build HAL with the latest changes and start manager service. Then run a computation and attempt to upload assets to the agent.

### In what environment did you encounter the issue?

When testing cocos with prism.

### Additional information you deem important

![image](https://github.com/user-attachments/assets/bb6b6f20-fa26-41e4-863a-ad638edfcebb)

**Comment by SammyOina** [comment]
this issue does not seem to be persistent, could be specific to your system or test setup, please update if the issue persists
