### ISSUE TITLE
Feature: Bring back `tmpfs` and disable swap

### ISSUE THREAD

**Issue by drasko** [ultravioletrs/cocos#263]
### Is your feature request related to a problem? Please describe.

No

### Describe the feature you are requesting, as well as the possible use case(s) for it.

`tmpfs` is newer than `ramfs`, and can be set to take the whole RAM partition in `fstab`:

```bash
tmpfs   /mnt/tmpfs   tmpfs   defaults,size=100%   0  0
```

Additionally, Linux swap can be disabled, again in `/etc/fstab`:

```bash
/swapfile   none    swap    sw    0   0
```

Use something like this in Buildroot to allow that we use `tmpfs`, but that is capable taking whole available RAM, and with swap turned off (not to write anything to disk).

### Indicate the importance of this feature to you.

Must-have

**Comment by drasko** [comment]
Actually, swap should be disabled in Buildroot during the kernel compilation, I think with `CONFIG_SWAP` flag:

```console
General Setup --->
  [ ] Support for paging of anonymous memory (swap)
```

Try if it possible to compile kernel with `tmpfs`, but with swap disabled already in Buildroot.

**Comment by danko-miladinovic** [comment]
This is fine for us to have. Because we have an in RAM VM, we do not have a disk, so swap is not being used. Currently the VM uses `ramfs` which does not have memory restrictions that `tmpfs` has. We can go back to `tmpfs` which is a small change, but I am still looking into a way to resize `tmpfs` in order to remove the memory limit. There is a way by re-mounting `tmpfs` file systems but I want to check if there is a way using kernel command line or some other easier way.

**Comment by drasko** [comment]
@danko-miladinovic does not the config with `fstab` as I mentioned [here](https://github.com/ultravioletrs/cocos/issues/263#issue-2551655407) resize the `tmpfs` to whole partition (100%)?

**Comment by danko-miladinovic** [comment]
Yes, but `fstab` only resizes one specific mount point based on the provided size parameter. It will not resize every file system that is `tmpfs`. If we want to resize every mount point that uses `tmpfs` then every one of them must be defined in `fstab`. 

Sorry, this is actually fine, we can resize the `/` or the root file system to be 100% of RAM size. The rest (`tmp`, `dev` ...) can be default 50% of RAM size. Is this fine? Our EOS has `tmp`, `dev` and `run` as separate `tmpfs` filesystems, meaning they are not part of the root file system.

**Comment by drasko** [comment]
Cool, then we can try it and see how it works.
