### ISSUE TITLE
Bug: "Update" Button Not Working on Computation Assets Page

### ISSUE THREAD

**Issue by FilipCivljak** [ultravioletrs/cocos#281]
### What were you trying to achieve?

I was trying to update a computation asset using the Update button on the Computation Assets page. However, the button is unresponsive, and no updates occur.

### What are the expected results?

When clicking the Update button, the computation asset should be updated successfully, and a confirmation message should appear.

### What are the received results?

After clicking the Update button, nothing happens—no visible process starts, no confirmation is shown.

### Steps To Reproduce

1. On the Computation Details page, I clicked on Assets Management.
2. It redirected me to the Computation Assets page.
3. I attempted to update a computation asset by clicking the Update button.
4. No action occurred

### In what environment did you encounter the issue?

Browser

**Comment by WashingtonKK** [comment]
Solved on this PR: https://github.com/ultravioletrs/prism/pull/531
