### ISSUE TITLE
Bug: Unable to Click Directly to Computation from Assets Page

### ISSUE THREAD

**Issue by FilipCivljak** [ultravioletrs/cocos#282]
### What were you trying to achieve?

On the User Assets page, I expected to be able to click on an asset and navigate directly to the associated computation.

### What are the expected results?

Clicking on an asset should allow me to directly navigate to the associated computation details.

### What are the received results?

There is no clickable link or button that allows direct navigation from an asset to its associated computation on the Assets page. 

### Steps To Reproduce

1. Go to the Assets page.
2. Attempt to click on any asset to navigate to its computation.

### In what environment did you encounter the issue?

Browser

### Additional information you deem important

![image](https://github.com/user-attachments/assets/a6e05f5f-1ff2-4989-98c5-5eb5845649f0)

**Comment by WashingtonKK** [comment]
Solved here: https://github.com/ultravioletrs/prism/pull/531
