### ISSUE TITLE
Switch from bytes to json on /run request on manager

### ISSUE THREAD

**Issue by SammyOina** [ultravioletrs/cocos#35]

**Comment by SammyOina** [comment]
@drasko @darkodraskovic since we have the notification/events service, we might not need this. Along with manifest being passed via qemu command,agent can simply update its status to the computations service and manager has no need to check the logs

**Comment by drasko** [comment]
This is not to update status, but really to start the VM. Manager must have `/run` endpoint which accepts Computation Manifest in the human-redable JSON. Then Manager will take this JSON and put it as a argument to the Linux kernel (via Qemu command line). Once kernel is booted, Agent will read this JSON (from somewhere within the kernel) and find over there the Manifest and all necessary certificates within the Manifest, including Computation Key (JWT) which it can use to authenticate to Computations service and its `/event` enpoint.

**Comment by SammyOina** [comment]
> This is not to update status, but really to start the VM. Manager must have `/run` endpoint which accepts Computation Manifest in the human-redable JSON. Then Manager will take this JSON and put it as a argument to the Linux kernel (via Qemu command line). Once kernel is booted, Agent will read this JSON (from somewhere within the kernel) and find over there the Manifest and all necessary certificates within the Manifest, including Computation Key (JWT) which it can use to authenticate to Computations service and its `/event` enpoint.

I meant the previous comment in reference to #36
