### ISSUE TITLE
Create JWT for each computation created to authenticate connection to /events endpoint

### ISSUE THREAD

**Issue by WashingtonKK** [ultravioletrs/cocos#37]

**Comment by drasko** [comment]
This is very similar to Thing Key in Magistrala - once Computation is created, then appropriate "Computation Key" is generated. This CK is then put in the Manifest and used by the Agent in the EOS to authenticate back in Computations service (i.e. Computations service will accept connections only from the Agent that has this Computation Key).

**Comment by WashingtonKK** [comment]
Closed since architecture was updated: https://github.com/ultravioletrs/cocos/issues/73
