### ISSUE TITLE
Add agent configuration on vsock

### ISSUE THREAD

**Issue by SammyOina** [ultravioletrs/cocos#49]
https://github.com/ultravioletrs/cocos/blob/200f20767319138dc65e49a7a13387a73084ddf1/init/systemd/cocos-agent.service#L9C37-L11

Agent needs notifications URL in the environment. This will need to be defined when building the image (HAL).

**Comment by drasko** [comment]
I think we do not need this. We can use default, or use one provided through kernel command line / vsoc.

I would like to avoid hard-coding this into the image, plus I am thinking that we switch back to DHCP and remove many problems that we are getting with static IP.

So we should add `agent_parameters` JSON in the Computation Manifest.

**Comment by drasko** [comment]
Since we are going to work on https://github.com/ultravioletrs/cocos/issues/55, we can use [vsock](https://wiki.qemu.org/Features/VirtioVsock) to pass the Computation manifest

**Comment by drasko** [comment]
https://github.com/mdlayher/vsock

https://mdlayher.com/blog/linux-vm-sockets-in-go/

**Comment by drasko** [comment]
https://medium.com/@F.DL/understanding-vsock-684016cf0eb0
