### ISSUE TITLE
Copying kernel and rootfs images

### ISSUE THREAD

**Issue by SammyOina** [ultravioletrs/cocos#52]
There is a potential issue with using the same images for multiple VMs, for example resource conflicts with logs which would be overiting each other as the instaces would be writing to the same files. 
 https://github.com/ultravioletrs/cocos/blob/cca75fc5cc57d5d7eb65930ecfd0a87b3c43e25c/init/systemd/cocos-agent.service#L6-L7

**Comment by drasko** [comment]
Can we append a computation ID to the name of the file - example: `agent-<cID>.out`. That way we'll be able to identify them, as we will have only one VM per computation. Alternatively - you can create a folder with computation ID and put files there `/var/log/cocos/<cID>/agent.stdout`
