### ISSUE TITLE
Failed to connect to Agent

### ISSUE THREAD

**Issue by danko-miladinovic** [ultravioletrs/cocos#88]
During the testing of attestation verification, the attestation report could not be fetched. After two reboots of the VM, it worked. In the agent logs, the following errors were found:

1. First boot: `2024/03/01 11:15:57 failed to create events service dial vsock host(2):9997: connect: connection reset by peer`
2. Second boot: `024/03/01 11:51:23 dial vsock host(2):9997: connect: connection reset by peer`

After the third boot, it worked.

**Comment by SammyOina** [comment]
@danko-miladinovic I am unable to replicate this issue
