### ISSUE TITLE
Replace python scripts with standalone binaries

### ISSUE THREAD

**Issue by SammyOina** [ultravioletrs/cocos#90]

**Comment by dborovcanin** [comment]
@SammyOina Let's explore what are the options for bundling Python algorithm **with dependencies** and sending it to the computation. That way we would simplify the approach only to be relevant for the version of system libraries, but as independent from the algorithm as possible.

**Comment by SammyOina** [comment]
> @SammyOina Let's explore what are the options for bundling Python algorithm **with dependencies** and sending it to the computation. That way we would simplify the approach only to be relevant for the version of system libraries, but as independent from the algorithm as possible.

One possibility is https://pypi.org/project/pyinstaller/

**Comment by SammyOina** [comment]
https://nuitka.net/

**Comment by SammyOina** [comment]
https://pypi.org/project/cx-Freeze/

**Comment by SammyOina** [comment]
> > @SammyOina Let's explore what are the options for bundling Python algorithm **with dependencies** and sending it to the computation. That way we would simplify the approach only to be relevant for the version of system libraries, but as independent from the algorithm as possible.
> 
> One possibility is https://pypi.org/project/pyinstaller/

This results in fairly large binaries for example the lin_reg example results in 18.9MB binary. Nuitka might do a better

**Comment by SammyOina** [comment]
> https://nuitka.net/

Nuikta resulted in a smaller binary 770kb but needs a fair amount of tweaking to make it work

**Comment by SammyOina** [comment]
Either way I think it is ok to remove the requirement for python as the runtime for algorithms and assume the user will bring their own binaries with all their requirements.

**Comment by danko-miladinovic** [comment]
The Agent could download dependencies before the algorithm is run. The dependencies could be a part of the manifest. But I agree, the user could send his own binarie.
